version: '3.8'
services:
  web:
    build:
      context: ../build/web
      dockerfile: Dockerfile
    ports:
      - "3206:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/shoppingnow
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    container_name: nosql-lab-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=shoppingnow
    volumes:
      - mongodb_data:/data/db
      - ../build/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 